name: Release Docker Image
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        token: ${{secrets.GITHUB_TOKEN}}
    - run: sudo apt update -qqy && sudo apt install -qqy wget
    - run: make releasedeps
    - run: git-semv now
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.pyama }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: make image
