name: publish-docker
on: [push]
jobs:
  build-and-push-to-regs:
    runs-on: ubuntu-20.04
    steps:
       -
         name: Set up Docker Buildx-e
         uses: docker/setup-buildx-action@v1
       -
         name: Login to DockerHub-e
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
         name: Build and push-e
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: elisescu/tty-proxy:latest
   
